### ISSUE TITLE
web folder not being created

### ISSUE THREAD

**Issue by SteveEmmerich** [etsuo/generator-hybrid#23]
I have run the generator multiple times and have not been able to get any files other than common and mobile. Is this correct? From what I saw in the generators code there should be a web folder as well.

**Comment by etsuo** [comment]
Hi @SteveEmmerich, thanks for the question. If you are using the current version by doing `npm install generator-hybrid`, then you are correct, the web project is not part of the install yet. Version 0.2.0 has the web project in it. It's almost done, but I haven't had time to work on it this week. I'm hoping to get it done and uploaded by Tuesday or Wednesday.

If you want to play around with the latest changes that will be released as 0.2.0, you can do the npm install directly from the develop branch like this: `npm install -g git+ssh://git@github.com:etsuo/generator-hybrid.git#develop`. Just keep in mind that development is still in progress. 

Thanks again for your question and let me know if you find any bugs or if you have any other problems.

**Comment by etsuo** [comment]
@SteveEmmerich 0.2.1 has the first pass at the web project. It's published to npm. Thanks for your feedback - let us know if you have any ideas, suggestions or problems.
