### ISSUE TITLE
Mobile native application for basic app is not displayed correctly

### ISSUE THREAD

**Issue by philipbrack** [etsuo/generator-hybrid#32]
When I perform

>gulp
>ionic build ios
>ionic run ios (or use xcode to pull it up)

the App only consumes about 4/5 of the real-estate of the phone.

**Comment by etsuo** [comment]
WoW... that's problematic... it's going to get expensive replacing screens if the generator consumes any percentage of the screen :p - i'll have a look at it today.

**Comment by etsuo** [comment]
![img_3852](https://cloud.githubusercontent.com/assets/6020168/12868026/c1eed6b8-ccb1-11e5-8012-bf857f543d19.PNG)
Here's the image you (@philipbrack) sent me earlier.
